CREATE TABLE IF NOT EXISTS "fodmap_table" (
    "name" TEXT,
    "sub_title" TEXT,
    "fodmap_mon" TEXT,
    "max_use" TEXT,
    "category" TEXT,
    "histamine" TEXT,
    "id" TEXT,
    "notes" TEXT
);
INSERT INTO "fodmap_table" VALUES ('Miód malinowy',NULL,'low','2 łyżki','cukry',NULL,'f_001',NULL),
	('Miód koniczynowy',NULL,'low','2 łyżki','cukry',NULL,'f_002',NULL),
	('Miód z bawełny',NULL,'low','2 łyżki','cukry',NULL,'f_003',NULL),
	('Miód ',NULL,'high',NULL,'cukry',NULL,'f_004',NULL),
	('Cukier trzcinowy',NULL,'high',NULL,'cukry',NULL,'f_005',NULL),
	('Cukier',NULL,'high',NULL,'cukry',NULL,'f_006',NULL),
	('Syrop klonowy',NULL,'high',NULL,'cukry',NULL,'f_007',NULL),
	('Syrop z agawy',NULL,'high',NULL,'cukry',NULL,'f_008',NULL),
	('Aspartam',NULL,'low',NULL,'cukry',NULL,'f_009',NULL),
	('Stewia (bez inuliny)',NULL,'low',NULL,'cukry',NULL,'f_010',NULL),
	('Glukoza',NULL,'low',NULL,'cukry',NULL,'f_011',NULL),
	('Syrop ryżowy',NULL,'low',NULL,'cukry',NULL,'f_012',NULL),
	('Cukier kokosowy',NULL,'mid','14g','cukry',NULL,'f_013',NULL),
	('Musztarda ','(sklepowa)','high',NULL,'dodatki',NULL,'f_014',NULL),
	('Musztarda','(domowej roboty / bez składników highFODMAP)','low',NULL,'dodatki',NULL,'f_015',NULL),
	('Majonez ','(domowej roboty / bez składników highFODMAP)','low',NULL,'dodatki',NULL,'f_016',NULL),
	('Majonez "sklepowy"',NULL,'high',NULL,'dodatki',NULL,'f_017',NULL),
	('Sos Tabasco',NULL,'low',NULL,'dodatki',NULL,'f_018',NULL),
	('Wasabi',NULL,'low',NULL,'dodatki',NULL,'f_019',NULL),
	('Ocet',NULL,'low',NULL,'dodatki',NULL,'f_020',NULL),
	('Ocet jabłkowy',NULL,'low',NULL,'dodatki',NULL,'f_021',NULL),
	('Ocet winny',NULL,'low',NULL,'dodatki',NULL,'f_022',NULL),
	('Ocet balsamiczny',NULL,'high',NULL,'dodatki',NULL,'f_023',NULL),
	('Sos sojowy',NULL,'high',NULL,'dodatki',NULL,'f_024',NULL),
	('Korzeń cykorii',NULL,'high',NULL,'dodatki',NULL,'f_025',NULL),
	('Przyprawy ','(z wyjątkiem czosnku i cebuli)','low',NULL,'dodatki',NULL,'f_026',NULL),
	('Bazylia',NULL,'low',NULL,'dodatki',NULL,'f_027',NULL),
	('Chilli',NULL,'low',NULL,'dodatki',NULL,'f_028',NULL),
	('Curry',NULL,'low',NULL,'dodatki',NULL,'f_029',NULL),
	('Czosnek niedźwiedzi',NULL,'low',NULL,'dodatki',NULL,'f_030',NULL),
	('Pieprz',NULL,'low',NULL,'dodatki',NULL,'f_031',NULL),
	('Mak',NULL,'low',NULL,'dodatki',NULL,'f_032',NULL),
	('Lawenda',NULL,'low',NULL,'dodatki',NULL,'f_033',NULL),
	('Lukrecja',NULL,'low',NULL,'dodatki',NULL,'f_034',NULL),
	('Sezam',NULL,'low',NULL,'dodatki',NULL,'f_035',NULL),
	('Szczypiorek',NULL,'low',NULL,'dodatki',NULL,'f_036',NULL),
	('Czekolada gorzka',NULL,'mid','80g','dodatki',NULL,'f_037',NULL),
	('Czekolada mleczna',NULL,'high',NULL,'dodatki','mid','f_038',NULL),
	('Bekon',NULL,'low',NULL,'mieso',NULL,'f_039',NULL),
	('Bekon ','(dosładzany fruktozą)','high',NULL,'mieso',NULL,'f_040',NULL),
	('Drób',NULL,'low',NULL,'mieso',NULL,'f_041',NULL),
	('Wołowina',NULL,'low',NULL,'mieso',NULL,'f_042',NULL),
	('Jaja',NULL,'low',NULL,'mieso','mid','f_043',NULL),
	('Ryba konserwowa',NULL,'high',NULL,'mieso','high','f_044',NULL),
	('Ryby',NULL,'low',NULL,'mieso','high','f_045',NULL),
	('Jagnięcina',NULL,'low',NULL,'mieso',NULL,'f_046',NULL),
	('Wieprzowina',NULL,'low',NULL,'mieso',NULL,'f_047',NULL),
	('Owoce morza',NULL,'low',NULL,'mieso','mid','f_048',NULL),
	('Szynki ','(i inne mięsa wysokoprzetworzone)','high',NULL,'mieso','high','f_049',NULL),
	('Maślanka',NULL,'high',NULL,'nabial',NULL,'f_050',NULL),
	('Ser camembert',NULL,'low',NULL,'nabial',NULL,'f_051',NULL),
	('Serek śmietankowy',NULL,'high',NULL,'nabial',NULL,'f_052',NULL),
	('Ser feta',NULL,'high',NULL,'nabial',NULL,'f_053',NULL),
	('Ser kozi',NULL,'high',NULL,'nabial',NULL,'f_054',NULL),
	('Ser haloumi',NULL,'mid','50g','nabial',NULL,'f_055',NULL),
	('Ser mozzarella',NULL,'high',NULL,'nabial',NULL,'f_056',NULL),
	('sery Żółte i dojrzewające','(z wyłączeniem pleśniowych)','low',NULL,'nabial','high','f_057',NULL),
	('Ser ricotta',NULL,'high',NULL,'nabial',NULL,'f_058',NULL),
	('Śmietana',NULL,'high',NULL,'nabial',NULL,'f_059',NULL),
	('Budyń',NULL,'high',NULL,'nabial',NULL,'f_060',NULL),
	('Lody',NULL,'high',NULL,'nabial',NULL,'f_061',NULL),
	('Kefir',NULL,'high',NULL,'nabial',NULL,'f_062',NULL),
	('Masło',NULL,'low',NULL,'nabial',NULL,'f_063',NULL),
	('Mleko',NULL,'high',NULL,'nabial','low','f_064',NULL),
	('Mleko bez laktozy',NULL,'mid',NULL,'nabial','low','f_065',NULL),
	('Jogurt','(sklepowy)','high',NULL,'nabial',NULL,'f_066',NULL),
	('Mleko migdałowe','Napój migdałowy','low',NULL,'nabial',NULL,'f_067',NULL),
	('Mleczko kokosowe',NULL,'low',NULL,'nabial',NULL,'f_068',NULL),
	('Mleko kokosowe','Napój kokosowy','mid','120g','nabial',NULL,'f_069',NULL),
	('Mleko z konopii','Napój z konopii','mid','240g','nabial',NULL,'f_070',NULL),
	('Mleko owsiane','Napój owsiany','mid','30g','nabial',NULL,'f_071',NULL),
	('Mleko ryżowe','Napój ryżowy','mid','200g','nabial',NULL,'f_072',NULL),
	('Mleko sojowe','Napój sojowy','high',NULL,'nabial',NULL,'f_073',NULL),
	('Kawa czarna','(w tym: decaf, rozpuszczalna)','low',NULL,'napoje',NULL,'f_074',NULL),
	('Kakao',NULL,'low',NULL,'napoje',NULL,'f_075',NULL),
	('Sok pomarańczowy',NULL,'high','75ml','napoje',NULL,'f_076',NULL),
	('Soki z owoców lowFODMAP',NULL,'low','125ml','napoje',NULL,'f_077',NULL),
	('Soki owocowe','(w tym m.in.: sok jabłkowy, sok pomarańczowy)','high',NULL,'napoje',NULL,'f_078',NULL),
	('Woda kokosowa',NULL,'mid','100g','napoje',NULL,'f_079',NULL),
	('Sok żurawinowy',NULL,'low',NULL,'napoje',NULL,'f_080',NULL),
	('Herbata czarna','(dozwolona tylko lekka)','low',NULL,'napoje',NULL,'f_081',NULL),
	('Herbata oolong',NULL,'high',NULL,'napoje',NULL,'f_082',NULL),
	('Rumianek','Napar z rumianku','high',NULL,'napoje',NULL,'f_083',NULL),
	('Rooibos','Herbata rooibos','low',NULL,'napoje',NULL,'f_084',NULL),
	('Herbata biała',NULL,'low',NULL,'napoje',NULL,'f_085',NULL),
	('Napar miętowy','Mięta, herbata miętowa','low',NULL,'napoje',NULL,'f_086',NULL),
	('Herbata zielona',NULL,'low',NULL,'napoje',NULL,'f_087',NULL),
	('Napar z miodokrzewu',NULL,'low',NULL,'napoje',NULL,'f_088',NULL),
	('Piwo',NULL,'high',NULL,'napoje','high','f_089',NULL),
	('Gin',NULL,'low',NULL,'napoje',NULL,'f_090',NULL),
	('Rum',NULL,'high',NULL,'napoje',NULL,'f_091',NULL),
	('Wódka',NULL,'low',NULL,'napoje',NULL,'f_092',NULL),
	('Whiskey','Whisky','low',NULL,'napoje',NULL,'f_093',NULL),
	('Tequila',NULL,'high',NULL,'napoje',NULL,'f_094',NULL),
	('Wino czerwone',NULL,'low',NULL,'napoje','high','f_095',NULL),
	('Wino musujące',NULL,'high',NULL,'napoje','high','f_096',NULL),
	('Wino, deserowe',NULL,'high',NULL,'napoje','high','f_097',NULL),
	('Wino słodkie',NULL,'high',NULL,'napoje','high','f_098',NULL),
	('Wino białe',NULL,'low',NULL,'napoje',NULL,'f_099',NULL),
	('Brandy',NULL,'high',NULL,'napoje',NULL,'f_100',NULL),
	('Migdały',NULL,'mid','12g','orzechy','mid','f_101',NULL),
	('Orzechy nerkowca','Nerkowce','high',NULL,'orzechy','mid','f_102',NULL),
	('Kasztany',NULL,'mid','168g','orzechy','mid','f_103',NULL),
	('Kasztany','(pieczone)','mid','84g','orzechy','mid','f_104',NULL),
	('Orzechy laskowe',NULL,'mid','15g','orzechy','mid','f_105',NULL),
	('Oczechy makadamia',NULL,'low',NULL,'orzechy','mid','f_106',NULL),
	('Orzechy brazylijskie',NULL,'mid','40g','orzechy','mid','f_107',NULL),
	('Orzeszki ziemne','Orzeszki arachidowe','low',NULL,'orzechy','mid','f_108',NULL),
	('Orzechy pecan',NULL,'mid','20g','orzechy','mid','f_109',NULL),
	('Oreszki piniowe',NULL,'mid','14g','orzechy','mid','f_110',NULL),
	('Pistacje',NULL,'high',NULL,'orzechy','mid','f_111',NULL),
	('Nasiona chia',NULL,'mid','24g','orzechy',NULL,'f_112',NULL),
	('Mak',NULL,'low',NULL,'orzechy',NULL,'f_113',NULL),
	('Pestki dyni',NULL,'mid','23g','orzechy',NULL,'f_114',NULL),
	('Sezam',NULL,'mid','11g','orzechy',NULL,'f_115',NULL),
	('Pestki  słonecznika',NULL,'mid','6g','orzechy',NULL,'f_116',NULL),
	('Orzechy włoskie',NULL,'mid','30g','orzechy','mid','f_117',NULL),
	('Falafel',NULL,'high',NULL,'orzechy',NULL,'f_118',NULL),
	('Kotlet z fasoli',NULL,'high',NULL,'orzechy','mid','f_119',NULL),
	('Quorn',NULL,'low',NULL,'orzechy','mid','f_120',NULL),
	('Tempeh, bez dodatków',NULL,'mid','100g','orzechy',NULL,'f_121',NULL),
	('Tofu, twarde',NULL,'low',NULL,'orzechy',NULL,'f_122',NULL),
	('Tofu jedwabiste',NULL,'high',NULL,'orzechy',NULL,'f_123',NULL),
	('Jabłka',NULL,'high',NULL,'owoce',NULL,'f_124',NULL),
	('Morela',NULL,'high',NULL,'owoce',NULL,'f_125',NULL),
	('Awokado',NULL,'mid','20g','owoce','mid','f_126',NULL),
	('Banan',NULL,'low',NULL,'owoce','mid','f_127',NULL),
	('Jeżyny',NULL,'high',NULL,'owoce',NULL,'f_128',NULL),
	('Borówki',NULL,'mid','20g','owoce',NULL,'f_129',NULL),
	('Breadfruit',NULL,'low',NULL,'owoce',NULL,'f_130',NULL),
	('Melon kantalupa',NULL,'mid','90g','owoce',NULL,'f_131',NULL),
	('Carambola',NULL,'low',NULL,'owoce',NULL,'f_132',NULL),
	('Wiśnie',NULL,'high',NULL,'owoce',NULL,'f_133',NULL),
	('Czereśnie',NULL,'high',NULL,'owoce',NULL,'f_134',NULL),
	('Klementynki',NULL,'low',NULL,'owoce','high','f_135',NULL),
	('Kokos',NULL,'mid','48g','owoce',NULL,'f_136',NULL),
	('Kumkwat',NULL,'mid','88g','owoce',NULL,'f_137',NULL),
	('Czerymoja',NULL,'high',NULL,'owoce',NULL,'f_138',NULL),
	('Pitaja','Dragon fruit, Smoczy owoc','low',NULL,'owoce',NULL,'f_139',NULL),
	('Durian',NULL,'low',NULL,'owoce',NULL,'f_140',NULL),
	('Figi, świeże',NULL,'high',NULL,'owoce',NULL,'f_141',NULL),
	('Winogrona thompson',NULL,'low',NULL,'owoce',NULL,'f_142',NULL),
	('Grejpfrut',NULL,'high',NULL,'owoce',NULL,'f_143',NULL),
	('Winogrona muscat',NULL,'low',NULL,'owoce',NULL,'f_144',NULL),
	('Winogrona czerwone',NULL,'low',NULL,'owoce',NULL,'f_145',NULL),
	('Guava, dojrzała',NULL,'low',NULL,'owoce',NULL,'f_146',NULL),
	('Kiwi, zielone',NULL,'mid','150g','owoce','mid','f_147',NULL),
	('Cytryna',NULL,'low',NULL,'owoce','high','f_148',NULL),
	('Limonka',NULL,'low',NULL,'owoce','high','f_149',NULL),
	('Liczi',NULL,'high',NULL,'owoce',NULL,'f_150',NULL),
	('Mandarynka',NULL,'low',NULL,'owoce','high','f_151',NULL),
	('Mango',NULL,'high',NULL,'owoce',NULL,'f_152',NULL),
	('Melon miodowy',NULL,'mid','90g','owoce',NULL,'f_153',NULL),
	('Nektarynka',NULL,'high',NULL,'owoce',NULL,'f_154',NULL),
	('Pomarańcze',NULL,'low',NULL,'owoce','high','f_155',NULL),
	('Marakuja',NULL,'mid','23g','owoce','high','f_156',NULL),
	('Brzoskwinia',NULL,'high',NULL,'owoce',NULL,'f_157',NULL),
	('Grusza chińska','Nashi','high',NULL,'owoce',NULL,'f_158',NULL),
	('Papaja',NULL,'low',NULL,'owoce',NULL,'f_159',NULL),
	('Kaki','Persymona','high',NULL,'owoce',NULL,'f_160',NULL),
	('Ananas',NULL,'low',NULL,'owoce',NULL,'f_161',NULL),
	('Plantan','Banan warzywny','low',NULL,'owoce',NULL,'f_162',NULL),
	('Śliwka',NULL,'high',NULL,'owoce','mid','f_163',NULL),
	('Granat',NULL,'mid','38g','owoce',NULL,'f_164',NULL),
	('Rambutan',NULL,'mid','31g','owoce',NULL,'f_165',NULL),
	('Malina',NULL,'mid','45g','owoce',NULL,'f_166',NULL),
	('Rabarbar',NULL,'low',NULL,'owoce',NULL,'f_167',NULL),
	('Karambola',NULL,'low',NULL,'owoce',NULL,'f_168',NULL),
	('Truskawka',NULL,'low',NULL,'owoce','high','f_169',NULL),
	('Tamarillo','Pomidor drzewiasty, Cyfomandra grubolistna','high',NULL,'owoce',NULL,'f_170',NULL),
	('Tamaryndowiec','Tamarynd','mid','8g','owoce',NULL,'f_171',NULL),
	('Arbuz',NULL,'high',NULL,'owoce',NULL,'f_172',NULL),
	('Jabłka suszone',NULL,'high',NULL,'owoce',NULL,'f_173',NULL),
	('Morele suszone',NULL,'high',NULL,'owoce',NULL,'f_174',NULL),
	('Banan suszony',NULL,'mid','20g','owoce','mid','f_175',NULL),
	('Kokos suszony','Czipsy z kokosa','mid','18g','owoce',NULL,'f_176',NULL),
	('Żyrawina, suszona',NULL,'mid','13g','owoce',NULL,'f_177',NULL),
	('Porzeczka',NULL,'mid','13g','owoce',NULL,'f_178',NULL),
	('Daktyle',NULL,'high',NULL,'owoce',NULL,'f_179',NULL),
	('Figi',NULL,'high',NULL,'owoce',NULL,'f_180',NULL),
	('Jagody Goji','(suszone)','high',NULL,'owoce',NULL,'f_181',NULL),
	('Guava','(w syropie)','mid','27g','owoce',NULL,'f_182',NULL),
	('Mango suszone',NULL,'high',NULL,'owoce',NULL,'f_184',NULL),
	('Mangostan',NULL,'high',NULL,'owoce',NULL,'f_185',NULL),
	('Gruszka',NULL,'high',NULL,'owoce',NULL,'f_186',NULL),
	('Ananas suszony',NULL,'high',NULL,'owoce',NULL,'f_187',NULL),
	('Śliwka suszony',NULL,'high',NULL,'owoce',NULL,'f_188',NULL),
	('Rodzynki',NULL,'mid','13g','owoce',NULL,'f_189',NULL),
	('Rodzynki sułtanki','Rodzynki sułtańskie','high',NULL,'owoce',NULL,'f_190',NULL),
	('Konfitury kupne',NULL,'high',NULL,'owoce',NULL,'f_191',NULL),
	('dżemy kupne',NULL,'high',NULL,'owoce',NULL,'f_192',NULL),
	('Konfitury domowe','(bez cukru)','low',NULL,'owoce',NULL,'f_193',NULL),
	('Dżemy domowe ','(bez cukru)','low',NULL,'owoce',NULL,'f_194',NULL),
	('Fasolka po bretońsku',NULL,'high',NULL,'straczki',NULL,'f_195',NULL),
	('Fasola czarna','(gotowana oraz z puszki)','high',NULL,'straczki',NULL,'f_196','W celu minimalizacji  objawów, wskazuje się ograniczenie spożycia produktów strączkowych.'),
	('Fasola żurawinowa','(z puszki)','high',NULL,'straczki',NULL,'f_197','W celu minimalizacji  objawów, wskazuje się ograniczenie spożycia produktów strączkowych.'),
	('Fasola biała półksiężycowata','(z puszki)','mid','35g','straczki',NULL,'f_198','W celu minimalizacji  objawów, wskazuje się ograniczenie spożycia produktów strączkowych.'),
	('Ciecierzyca Chana Dal','(gotowana)','low',NULL,'straczki',NULL,'f_199','W celu minimalizacji  objawów, wskazuje się ograniczenie spożycia produktów strączkowych.'),
	('Ciecierzyca','(z puszki)','mid','42g','straczki',NULL,'f_200','W celu minimalizacji  objawów, wskazuje się ograniczenie spożycia produktów strączkowych.'),
	('Ciecierzyca Garbanzo','(z puszki)','mid','42g','straczki',NULL,'f_201','W celu minimalizacji  objawów, wskazuje się ograniczenie spożycia produktów strączkowych.'),
	('Fasola biała Haricot','(gotowana)','high',NULL,'straczki',NULL,'f_202','W celu minimalizacji  objawów, wskazuje się ograniczenie spożycia produktów strączkowych.'),
	('Soczewica, ','(z puszki)','low',NULL,'straczki','low','f_203','W celu minimalizacji  objawów, wskazuje się ograniczenie spożycia produktów strączkowych.'),
	('Soczewica, zielona','(gotowana)','mid','23g','straczki','low','f_204','W celu minimalizacji  objawów, wskazuje się ograniczenie spożycia produktów strączkowych.'),
	('Soczewica, czerwona','(gotowana)','mid','23g','straczki',NULL,'f_205','W celu minimalizacji  objawów, wskazuje się ograniczenie spożycia produktów strączkowych.'),
	('Fasola biała półksiężycowata','(gotowana)','mid','39g','straczki',NULL,'f_206','W celu minimalizacji  objawów, wskazuje się ograniczenie spożycia produktów strączkowych.'),
	('Fasola Mung',NULL,'mid','53g','straczki',NULL,'f_207','W celu minimalizacji  objawów, wskazuje się ograniczenie spożycia produktów strączkowych.'),
	('Fasola czerwona','(gotowana)','high',NULL,'straczki',NULL,'f_208','W celu minimalizacji  objawów, wskazuje się ograniczenie spożycia produktów strączkowych.'),
	('Soja gotowana',NULL,'high',NULL,'straczki','low','f_209','W celu minimalizacji  objawów, wskazuje się ograniczenie spożycia produktów strączkowych.'),
	('Gorch łuskany','(gotowany)','high',NULL,'straczki',NULL,'f_210','W celu minimalizacji  objawów, wskazuje się ograniczenie spożycia produktów strączkowych.'),
	('Fasola Urid Dal','(gotowana)','low',NULL,'straczki',NULL,'f_211','W celu minimalizacji  objawów, wskazuje się ograniczenie spożycia produktów strączkowych.'),
	('Olej palmowy',NULL,'low',NULL,'tluszcze',NULL,'f_212','W celu minimalizacji  objawów, wskazuje się ograniczenie spożycia produktów strączkowych.'),
	('Olej kokosowy',NULL,'low',NULL,'tluszcze',NULL,'f_213',NULL),
	('Oliwa z oliwek',NULL,'low',NULL,'tluszcze',NULL,'f_214',NULL),
	('Smalec',NULL,'low',NULL,'tluszcze',NULL,'f_215',NULL),
	('Oleje słonecznikowy',NULL,'low',NULL,'tluszcze',NULL,'f_216',NULL),
	('Inne oleje roślinne',NULL,'low',NULL,'tluszcze',NULL,'f_217',NULL),
	('Pieczarki',NULL,'high',NULL,'warzywa','low','f_218',NULL),
	('Pieczarki Portobello',NULL,'high',NULL,'warzywa','low','f_219',NULL),
	('Grzyby Shiitake',NULL,'high',NULL,'warzywa','low','f_220',NULL),
	('Okra',NULL,'mid','60g','warzywa',NULL,'f_221',NULL),
	('Cebula',NULL,'high',NULL,'warzywa',NULL,'f_222',NULL),
	('Pasternak',NULL,'low',NULL,'warzywa',NULL,'f_223',NULL),
	('Groszek cukrowy',NULL,'mid','17g','warzywa',NULL,'f_224',NULL),
	('Froszek cukrowy odmiany Snap Pea',NULL,'high',NULL,'warzywa',NULL,'f_225',NULL),
	('Groszek, mrożony',NULL,'high',NULL,'warzywa',NULL,'f_226',NULL),
	('Ziemniak',NULL,'high',NULL,'warzywa',NULL,'f_227',NULL),
	('Batat','Słodki ziemniak','high','70g','warzywa',NULL,'f_228','Sprzeczne informacje na temat zawartości FODMAP w źródłach.'),
	('Dynia piżmowa ','Butternut','mid','30g','warzywa',NULL,'f_229',NULL),
	('Dynia japońska','Hokkaido','low',NULL,'warzywa',NULL,'f_230',NULL),
	('Rzodkiew',NULL,'low',NULL,'warzywa',NULL,'f_231',NULL),
	('Brukiew',NULL,'mid','65g','warzywa',NULL,'f_232',NULL),
	('Burak liściowy','Boćwina','low',NULL,'warzywa',NULL,'f_233',NULL),
	('Szpinak',NULL,'mid','38g','warzywa','high','f_234',NULL),
	('Patison',NULL,'low',NULL,'warzywa',NULL,'f_235',NULL),
	('Dynia makaronowa',NULL,'mid','155g','warzywa',NULL,'f_236',NULL),
	('Taro',NULL,'mid','82g','warzywa',NULL,'f_237',NULL),
	('Pomidorki cherry',NULL,'low','68g','warzywa','high','f_238',NULL),
	('Pomidory',NULL,'low',NULL,'warzywa','high','f_239',NULL),
	('Rzepa',NULL,'mid','65g','warzywa',NULL,'f_240',NULL),
	('Yam',NULL,'mid','164g','warzywa',NULL,'f_241',NULL),
	('Jukka',NULL,'mid','69g','warzywa',NULL,'f_242',NULL),
	('Cukinia',NULL,'mid','66g','warzywa',NULL,'f_243',NULL),
	('Pędy bambusa, z puszki',NULL,'low',NULL,'warzywa',NULL,'f_244',NULL),
	('Edamame',NULL,'low',NULL,'warzywa',NULL,'f_245',NULL),
	('Ogórki konserwowe','Ogórki kiszone','high',NULL,'warzywa',NULL,'f_246',NULL),
	('Ogórki konserwowe bez cukru i czosnku','Ogórki kiszone bez cukru i czosnku','low',NULL,'warzywa',NULL,'f_247',NULL),
	('Pieczarki z puszki',NULL,'mid','110g','warzywa','low','f_248',NULL),
	('Grzyby Shiitake, suszone',NULL,'mid','7g','warzywa',NULL,'f_249',NULL),
	('Oliwki, zielone, bez pestek',NULL,'low',NULL,'warzywa',NULL,'f_250',NULL),
	('Cebula marynowana',NULL,'high',NULL,'warzywa',NULL,'f_251',NULL);
INSERT INTO "fodmap_table" VALUES ('Kluski ziemniaczane, pyzy',NULL,'low',NULL,'warzywa',NULL,'f_252',NULL),
	('Dynia, z puszki',NULL,'mid','60g','warzywa',NULL,'f_253',NULL),
	('Wodorosty nori',NULL,'high',NULL,'warzywa',NULL,'f_254',NULL),
	('Pomidor, z puszki',NULL,'high',NULL,'warzywa',NULL,'f_255',NULL),
	('Pomidor, suszony',NULL,'mid','8g','warzywa',NULL,'f_256',NULL),
	('Kapusta kiszona',NULL,'mid','20g','warzywa',NULL,'f_257',NULL),
	('Alfalfa',NULL,'low',NULL,'warzywa',NULL,'f_258',NULL),
	('Rukola',NULL,'low',NULL,'warzywa',NULL,'f_259',NULL),
	('Karczoch, cały',NULL,'high',NULL,'warzywa',NULL,'f_260',NULL),
	('Serca karczocha, z puszki',NULL,'mid','28g','warzywa',NULL,'f_261',NULL),
	('Szparag',NULL,'high',NULL,'warzywa',NULL,'f_262',NULL),
	('Bakłażan',NULL,'mid','41g','warzywa',NULL,'f_263',NULL),
	('Pędy bambusa,  świeżę',NULL,'low',NULL,'warzywa',NULL,'f_264',NULL),
	('Pędy fasoli',NULL,'low',NULL,'warzywa',NULL,'f_265',NULL),
	('Fasolka zielona',NULL,'mid','86g','warzywa',NULL,'f_266',NULL),
	('Burak',NULL,'mid','20g','warzywa',NULL,'f_267',NULL),
	('Papryka, zielona',NULL,'mid','52g','warzywa',NULL,'f_268',NULL),
	('Papryka, czerwona',NULL,'low',NULL,'warzywa',NULL,'f_269',NULL),
	('Kapusta chińska',NULL,'mid','85g','warzywa',NULL,'f_270',NULL),
	('Brokuł',NULL,'mid','47g','warzywa',NULL,'f_271',NULL),
	('Brukselka',NULL,'mid','38g','warzywa',NULL,'f_272',NULL),
	('Kapusta',NULL,'mid','94g','warzywa',NULL,'f_273',NULL),
	('Marchew',NULL,'low',NULL,'warzywa',NULL,'f_274',NULL),
	('Cassava','Maniok jadalny','mid','69g','warzywa',NULL,'f_275',NULL),
	('Kalafior',NULL,'high',NULL,'warzywa',NULL,'f_276',NULL),
	('Seler korzeniowy',NULL,'low',NULL,'warzywa',NULL,'f_277',NULL),
	('Seler naciowy',NULL,'mid','12g','warzywa',NULL,'f_278',NULL),
	('Chili, zielone',NULL,'low',NULL,'warzywa',NULL,'f_279',NULL),
	('Chili, czerwone',NULL,'mid','28g','warzywa',NULL,'f_280',NULL),
	('Szczypiorek',NULL,'low',NULL,'warzywa',NULL,'f_281',NULL),
	('Kapusta galicyjska',NULL,'low',NULL,'warzywa',NULL,'f_282',NULL),
	('Kukurydza cukrowa',NULL,'mid','43g','warzywa',NULL,'f_283',NULL),
	('Kabaczek',NULL,'mid','66g','warzywa',NULL,'f_284',NULL),
	('Ogórek',NULL,'low',NULL,'warzywa',NULL,'f_285',NULL),
	('Brokuł chiński','Gai lan','mid','68g','warzywa',NULL,'f_286',NULL),
	('Czosnek',NULL,'high',NULL,'warzywa',NULL,'f_287',NULL),
	('Imbir','(korzeń)','low',NULL,'warzywa',NULL,'f_288',NULL),
	('Jarmuż',NULL,'low',NULL,'warzywa',NULL,'f_289',NULL),
	('Por, bulwa',NULL,'high',NULL,'warzywa',NULL,'f_290',NULL),
	('Por, liście',NULL,'mid','28g','warzywa',NULL,'f_291',NULL),
	('Sałata maślana',NULL,'low',NULL,'warzywa',NULL,'f_292',NULL),
	('Sałata lodowa',NULL,'low',NULL,'warzywa',NULL,'f_293',NULL),
	('Cykoria radicchio','Cykoria czerwona, sałatowa','mid','35g','warzywa',NULL,'f_294',NULL),
	('Groch cukrowy',NULL,'mid','17g','warzywa',NULL,'f_295',NULL),
	('Otręby pszenne',NULL,'mid','5g','zboza',NULL,'f_296',NULL),
	('Kasza gryczana',NULL,'low',NULL,'zboza',NULL,'f_297',NULL),
	('Gryka',NULL,'mid','27g','zboza',NULL,'f_298',NULL),
	('Kuskus',NULL,'mid','37g','zboza',NULL,'f_299',NULL),
	('Kasza jaglana',NULL,'low',NULL,'zboza',NULL,'f_300',NULL),
	('Płatki owsiane','(nie błyskawiczne)','mid','60g','zboza',NULL,'f_301',NULL),
	('Polenta ',NULL,'low',NULL,'zboza',NULL,'f_302',NULL),
	('Quinoa',NULL,'low',NULL,'zboza',NULL,'f_303',NULL),
	('Wafle ryżowe',NULL,'high',NULL,'zboza',NULL,'f_304',NULL),
	('Ryż','biały, basmati, jaśminowy','low',NULL,'zboza',NULL,'f_305',NULL),
	('Orkisz',NULL,'high',NULL,'zboza',NULL,'f_306',NULL),
	('Mąka migdałowa',NULL,'mid','24g','zboza',NULL,'f_307',NULL),
	('Mąka z amarantusa',NULL,'high',NULL,'zboza',NULL,'f_308',NULL),
	('Mąka jęczmienna',NULL,'high',NULL,'zboza',NULL,'f_309',NULL),
	('Mąka gryczana',NULL,'low',NULL,'zboza',NULL,'f_310',NULL),
	('Mąka kukurydziana',NULL,'low',NULL,'zboza',NULL,'f_311',NULL),
	('Mąka z pszenicy samopsza',NULL,'high',NULL,'zboza',NULL,'f_312',NULL),
	('Płatki kukurydziane',NULL,'mid',NULL,'zboza',NULL,'f_313',NULL),
	('Mąka kamut',NULL,'high',NULL,'zboza',NULL,'f_314',NULL),
	('Mąka łubinowa',NULL,'high',NULL,'zboza',NULL,'f_315',NULL),
	('Mąka jaglana',NULL,'low',NULL,'zboza',NULL,'f_316',NULL),
	('Mąka z Qinoa',NULL,'low',NULL,'zboza',NULL,'f_317',NULL),
	('Mąka ryżowa',NULL,'low',NULL,'zboza',NULL,'f_318',NULL),
	('Mąka żytnia',NULL,'high',NULL,'zboza',NULL,'f_319',NULL),
	('Mąka z sorgo',NULL,'low',NULL,'zboza',NULL,'f_320',NULL),
	('Mąka orkiszowa',NULL,'high',NULL,'zboza',NULL,'f_321',NULL),
	('Płatki kukurydziane bez glutenu',NULL,'low',NULL,'zboza',NULL,'f_322',NULL),
	('Mąka teff',NULL,'low',NULL,'zboza',NULL,'f_323',NULL),
	('Mąka pszenna',NULL,'high',NULL,'zboza',NULL,'f_324',NULL),
	('Mąka z pochrzynu',NULL,'low',NULL,'zboza',NULL,'f_325',NULL),
	('Skrobia kukurydziana',NULL,'low',NULL,'zboza',NULL,'f_326',NULL),
	('Skrobia ziemniaczana',NULL,'low',NULL,'zboza',NULL,'f_327',NULL),
	('Skrobia z tapioki',NULL,'low',NULL,'zboza',NULL,'f_328',NULL),
	('Musli',NULL,'high',NULL,'zboza',NULL,'f_329',NULL),
	('Ryż prażony',NULL,'mid',NULL,'zboza',NULL,'f_330',NULL),
	('Otręby pszenne',NULL,'high',NULL,'zboza',NULL,'f_331',NULL),
	('Kasza pęczak',NULL,'high',NULL,'zboza',NULL,'f_332',NULL),
	('Kasza bulgur',NULL,'mid','44g','zboza',NULL,'f_333',NULL);
