
type InputTypes = {
    name: string,
    prep_time: number | null,
    amount: string,
    equipment: string,
    categories: string[],
    description: string,
    recipe_text: string,
    photo: string,
    author: string,
    date: Date | null, // to be hidden
    ratings: number[],
    ingredient_1_name: string,
    ingredient_1_amount: string,
    ingredient_2_name: string,
    ingredient_2_amount: string,
    ingredient_3_name: string,
    ingredient_3_amount: string,
    ingredient_4_name: string,
    ingredient_4_amount: string,
    ingredient_5_name: string,
    ingredient_5_amount: string,
    ingredient_6_name: string,
    ingredient_6_amount: string,
    ingredient_7_name: string,
    ingredient_7_amount: string,
    ingredient_8_name: string,
    ingredient_8_amount: string,
    ingredient_9_name: string,
    ingredient_9_amount: string,
    ingredient_10_name: string,
    ingredient_10_amount: string,
    ingredient_11_name: string,
    ingredient_11_amount: string,
    ingredient_12_name: string,
    ingredient_12_amount: string,
    ingredient_13_name: string,
    ingredient_13_amount: string,
    ingredient_14_name: string,
    ingredient_14_amount: string,
    ingredient_15_name: string,
    ingredient_15_amount: string,
    verified: boolean,
    id: string,
  }
  
  export default InputTypes